language: cpp

sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost1.55-all-dev
      - libopenmpi-dev

script:
  - mkdir build
  - cd build
  - CXX=g++-7 cmake ..
  - make
